name: Deploy to EC2

on:
  push:
    branches:
      - main  # main branch'teki push işlemlerinde tetiklenir

jobs:
  deploy:
    runs-on: ubuntu-latest  # İş Ubuntu işletim sisteminde çalışacak

    steps:
    - name: Checkout code  # Kodu kontrol et
      uses: actions/checkout@v3  # GitHub Actions'dan v3 sürümünü kullan

    - name: Copy files via SSH  # Dosyaları EC2'ye kopyala
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2'nin public IP'si
        username: ubuntu  # EC2 instance'ının varsayılan kullanıcı adı
        key: ${{ secrets.EC2_SSH_KEY }}  # EC2'ye bağlanmak için kullanılan SSH private key
        source: "."  # Kopyalanacak dosyalar (mevcut dizindeki her şey)
        target: "/home/ubuntu/jenkins-simple-app"  # Dosyaların EC2'de kopyalanacağı dizin

    - name: Execute command via SSH  # EC2'de komut çalıştır
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2'nin public IP'si
        username: ubuntu  # EC2 instance'ının varsayılan kullanıcı adı
        key: ${{ secrets.EC2_SSH_KEY }}  # EC2'ye bağlanmak için kullanılan SSH private key
        script: |
          cd /home/ubuntu/jenkins-simple-app  # Uygulamanın bulunduğu dizine geç
          npm install  # Gerekli bağımlılıkları yükle
          pm2 restart index.js  # Uygulamayı PM2 ile yeniden başlat
